### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by mtharrison** [tmcw/literate-raytracer#10]
Hey, just to let you know I took your Ray tracer and extended it and ported it to WebAssembly and wrote about it here: http://matt-harrison.com/raytracing-webassembly-vs-javascript/.

There's a demo here too: https://mtharrison.github.io/wasm-raytracer/

I couldn't have understood the principles so quickly without your great tutorial, so thanks!

**Comment by tmcw** [comment]
Awesome - so cool!
