### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by infernalmaster** [tmcw/literate-raytracer#11]
https://github.com/tmcw/literate-raytracer/blob/gh-pages/index.js#L344

```
for (var i = 0; i < scene.lights.length; i++) {
   var lightPoint = scene.lights[0];
```

Looks like it should use `i`:
```
var lightPoint = scene.lights[i];
```

So the same in description https://github.com/tmcw/literate-raytracer/blob/gh-pages/index.html#L732

**Comment by tmcw** [comment]
Thanks! Mind creating a PR?

**Comment by infernalmaster** [comment]
done!
